// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: avf/v1/transform.proto

package avfv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransformRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformRequest) Reset() {
	*x = TransformRequest{}
	mi := &file_avf_v1_transform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformRequest) ProtoMessage() {}

func (x *TransformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avf_v1_transform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformRequest.ProtoReflect.Descriptor instead.
func (*TransformRequest) Descriptor() ([]byte, []int) {
	return file_avf_v1_transform_proto_rawDescGZIP(), []int{0}
}

type TransformResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformResponse) Reset() {
	*x = TransformResponse{}
	mi := &file_avf_v1_transform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformResponse) ProtoMessage() {}

func (x *TransformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avf_v1_transform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformResponse.ProtoReflect.Descriptor instead.
func (*TransformResponse) Descriptor() ([]byte, []int) {
	return file_avf_v1_transform_proto_rawDescGZIP(), []int{1}
}

var File_avf_v1_transform_proto protoreflect.FileDescriptor

const file_avf_v1_transform_proto_rawDesc = "" +
	"\n" +
	"\x16avf/v1/transform.proto\x12\x06avf.v1\"\x12\n" +
	"\x10TransformRequest\"\x13\n" +
	"\x11TransformResponse2`\n" +
	"\x10TransformService\x12L\n" +
	"\x0fTransformStream\x12\x18.avf.v1.TransformRequest\x1a\x19.avf.v1.TransformResponse\"\x00(\x010\x01B\x8b\x01\n" +
	"\n" +
	"com.avf.v1B\x0eTransformProtoP\x01Z4github.com/brian14708/gst-server/sdk/go/avf/v1;avfv1\xa2\x02\x03AXX\xaa\x02\x06Avf.V1\xca\x02\x06Avf\\V1\xe2\x02\x12Avf\\V1\\GPBMetadata\xea\x02\aAvf::V1b\x06proto3"

var (
	file_avf_v1_transform_proto_rawDescOnce sync.Once
	file_avf_v1_transform_proto_rawDescData []byte
)

func file_avf_v1_transform_proto_rawDescGZIP() []byte {
	file_avf_v1_transform_proto_rawDescOnce.Do(func() {
		file_avf_v1_transform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_avf_v1_transform_proto_rawDesc), len(file_avf_v1_transform_proto_rawDesc)))
	})
	return file_avf_v1_transform_proto_rawDescData
}

var (
	file_avf_v1_transform_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
	file_avf_v1_transform_proto_goTypes  = []any{
		(*TransformRequest)(nil),  // 0: avf.v1.TransformRequest
		(*TransformResponse)(nil), // 1: avf.v1.TransformResponse
	}
)

var file_avf_v1_transform_proto_depIdxs = []int32{
	0, // 0: avf.v1.TransformService.TransformStream:input_type -> avf.v1.TransformRequest
	1, // 1: avf.v1.TransformService.TransformStream:output_type -> avf.v1.TransformResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_avf_v1_transform_proto_init() }
func file_avf_v1_transform_proto_init() {
	if File_avf_v1_transform_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_avf_v1_transform_proto_rawDesc), len(file_avf_v1_transform_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_avf_v1_transform_proto_goTypes,
		DependencyIndexes: file_avf_v1_transform_proto_depIdxs,
		MessageInfos:      file_avf_v1_transform_proto_msgTypes,
	}.Build()
	File_avf_v1_transform_proto = out.File
	file_avf_v1_transform_proto_goTypes = nil
	file_avf_v1_transform_proto_depIdxs = nil
}
